name: Standalone

on: [push, pull_request]

jobs:
  standalone-deployment-mongosh:
    name: Standalone (mongosh)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        id: tomodo
        uses: ./
        with:
          name: "test"

      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Connect to tomodo instance
        run: |
          mongosh "$CONNECTION_STRING" --eval 'db.adminCommand({ ping: 1})' --quiet
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}

  standalone-deployment-python:
    name: Standalone (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        id: tomodo
        uses: ./
        with:
          name: "test"

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyMongo
        run: pip install pymongo

      - name: Connect to tomodo instance
        run: |
          python - <<EOF
          import os
          from sys import exit
          from pymongo import MongoClient

          client = MongoClient(os.environ.get('CONNECTION_STRING'))
          res = client.admin.command("ping")
          exit(1) if not int(res["ok"]) == 1 else print("ok")
          EOF
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}

  standalone-ephemeral:
    name: Standalone (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        id: tomodo
        uses: ./
        with:
          name: "test"
          ephemeral: "true"

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyMongo
        run: pip install pymongo

      - name: Connect to tomodo instance
        run: |
          python - <<EOF
          import os
          from sys import exit
          from pymongo import MongoClient

          client = MongoClient(os.environ.get('CONNECTION_STRING'))
          res = client.admin.command("ping")
          exit(1) if not int(res["ok"]) == 1 else print("ok")
          EOF
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}

  standalone-port:
    name: Standalone with non-standard port
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        id: tomodo
        uses: ./
        with:
          name: "test"
          port: 27000
          instance-type: standalone

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyMongo
        run: pip install pymongo

      - name: Connect to tomodo instance
        run: |
          python - <<EOF
          import os
          from sys import exit
          from pymongo import MongoClient

          client = MongoClient(os.environ.get('CONNECTION_STRING'))
          res = client.admin.command("ping")
          exit(1) if not int(res["ok"]) == 1 else print("ok")
          EOF
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}

  standalone-with-authn:
    name: Standalone with authentication
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        uses: ./
        id: tomodo
        with:
          name: "test"
          username: "mongouser"
          password: "thisisnotsafe"
          instance-type: standalone

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyMongo
        run: pip install pymongo

      - name: Connect to tomodo instance
        run: |
          python - <<EOF
          import os
          from sys import exit
          from pymongo import MongoClient

          client = MongoClient(os.environ.get('CONNECTION_STRING'))
          res = client.admin.command("ping")
          exit(1) if not int(res["ok"]) == 1 else print("ok")
          EOF
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}

  standalone-image-tag:
    name: Standalone with non-latest image tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        uses: ./
        id: tomodo
        with:
          name: "test"
          image-tag: "6.0"
          instance-type: standalone

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyMongo
        run: pip install pymongo

      - name: Connect to tomodo instance
        run: |
          python - <<EOF
          import os
          from sys import exit
          from pymongo import MongoClient

          client = MongoClient(os.environ.get('CONNECTION_STRING'))
          res = client.admin.command("ping")
          exit(1) if not int(res["ok"]) == 1 else print("ok")
          EOF
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}

  standalone-network:
    name: Standalone with network name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        uses: ./
        id: tomodo
        with:
          name: "test"
          network-name: "some-non-default-network"
          instance-type: standalone

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install PyMongo
        run: pip install pymongo

      - name: Connect to tomodo instance
        run: |
          python - <<EOF
          import os
          from sys import exit
          from pymongo import MongoClient

          client = MongoClient(os.environ.get('CONNECTION_STRING'))
          res = client.admin.command("ping")
          exit(1) if not int(res["ok"]) == 1 else print("ok")
          EOF
        env:
          CONNECTION_STRING: ${{ steps.tomodo.outputs.connection-string }}
